### ISSUE TITLE
No settings.yml.example in source

### ISSUE THREAD

**Issue by paulmwatson** [sunlightlabs/datajam#1]
I'm trying to follow the Heroku instructions which mention copying the settings.yml.example file in config. But no such file exists.

**Comment by luigi** [comment]
We're practicing README-driven development. The Heroku stuff isn't ready yet. :)

**Comment by paulmwatson** [comment]
haha fair enough. I'll follow the project, sounds very interesting thank you.

**Comment by luigi** [comment]
In case I don't remember to ping you when it's ready for use, we'll definitely make an announcement on the Sunlight Labs blog.

http://sunlightlabs.com
