### ISSUE TITLE
Event Reminders

### ISSUE THREAD

**Issue by luigi** [sunlightlabs/datajam#11]
Admins should be able to add a form for event reminders to an event page. For a styling hook, the form should have `class='reminder_form'`. It will ask the viewer for an email address. A viewer who submits an email address will be sent an email one hour before the event's `scheduled_at` value.

The event reminder form should be inserted into an event template via a pre-defined Handlebars variable like `{{ event_reminder }}`.

If the event has begun, the reminder form is hidden from the page via JavaScript. If the event is re-rendered to the cache after the event begins, the reminder form should not be rendered.

This will require a background task.

**Comment by elcuervo** [comment]
Is there any background task at the moment? (in case i'm missing something)

**Comment by elcuervo** [comment]
What kind of message should be sent?

**Comment by drinks** [comment]
Emails should be sent to the reminder queue for an event at the specified interval before the event begins. The deployment target is heroku, so the cron add-on will call a rake task to generate and send these emails. An admin page should display/provide crud for the list of subscribed emails for each event.

**Comment by elcuervo** [comment]
I'm wrapping up the story right now. Is there any mail user you plan to use?

**Comment by drinks** [comment]
Given heroku constraints, mail should be sent with sendgrid or mailgun. Realizing now this would have been good to mention sooner. Hopefully this doesn't cause too much backtracking. I'm leaning toward sendgrid currently based solely on pricing, but if one has better libraries than the other, feel free to make that call.

**Comment by elcuervo** [comment]
No problem, just checking which mail provider we are going to use.

**Comment by luigi** [comment]
Can't the Sunlight SMTP server be used? (and other orgs would have to use their own)

http://devcenter.heroku.com/articles/smtp

**Comment by drinks** [comment]
@luigi, perhaps, is there an SMTP server for app consumption?  All my projects use postmark, which is also an option.

**Comment by drinks** [comment]
Let's build sendgrid into datajam and we'll adapt for postmark in our deployment repo.

**Comment by elcuervo** [comment]
Is there any template for the reminder mail? or should i write something until we change it?

**Comment by drinks** [comment]
@elcuervo an html template listing the available vars to start would be great. Templates should render with handlebars.

**Comment by elcuervo** [comment]
The rake task it's called notifications:send_reminders and the template it's located in app/views/notifications_mailer/event_reminder.
As discussed the current config expects sendgrid

**Comment by drinks** [comment]
The commit looks good, but I'm unable to test due to the handlebars error introduced in #10. Any breakthroughs there?

**Comment by elcuervo** [comment]
I'll take a look to that issue.

**Comment by drinks** [comment]
The reminder form appears to be getting escaped on render: https://skitch.com/dndrnkrd/8frh9/skitched-20120227-111844

**Comment by elcuervo** [comment]
Handlebars uses {{ }} to print escaped content {{{ }}} will print it as is, do you want me to change it?

**Comment by drinks** [comment]
derp. I'll get it, thanks.
