### ISSUE TITLE
Integrate with Sunlight Metrics API

### ISSUE THREAD

**Issue by luigi** [sunlightlabs/datajam#13]
Sunlight has created an API for organization-wide metrics reporting. Sunlight's instance of Datajam (Sunlight Live) needs to report usage metrics to this metrics API.

This may be most practical as a one-off script that's run once a night.

Tom Lee will have more details on the exact needs. Sunlight developer Daniel Cloud (dcloud at sunlightfoundation.com) is the point of contact for the metrics API.

**Comment by drinks** [comment]
The overall stats for sunlightlive.com are currently reported here. Lapidus is not currently configured for event tracking and broken down stats by event, so finishing this ticket per spec may need to be bumped to a later milestone

**Comment by drinks** [comment]
Closing, stats will stay in GA.
