### ISSUE TITLE
Re-style /admin area using Twitter bootstrap

### ISSUE THREAD

**Issue by luigi** [sunlightlabs/datajam#14]
Use version 2.0:

http://www.markdotto.com/2012/01/24/bootstrap-2-ready-for-testing-and-feedback/

**Comment by drinks** [comment]
I've committed the bootstrap 2 assets to the project, and broken out the header nav into 3 groups that can be menu bar dropdowns.

**Comment by drinks** [comment]
When this ticket gets tackled, attention should be paid to the admin forms and their error messages. Currently the level of error notification is insufficient.

**Comment by drinks** [comment]
Some specs:
- Use the fluid layout w/ sidebar: https://skitch.com/dndrnkrd/88a9i/skitched-20120306-170307. Appropriate icons should appear to the left of the links if available.
- Buttons should use the `btn` class appropriately. Primary actions should use `.btn-primary`, deletion should use `.btn-danger`, etc.
- Disabled deletion buttons are currently not being shown for templates that cannot be deleted. This should be changed to show a `.disabled` button and perform no action on click
- Tables: let's start with zebra-striped, no borders as in example 2 in the bootstrap docs, and see how that looks.
- Forms: should use the Horizontal form layout in the docs. If possible, the Cloud 9 editor should be made to work with fluid dimensions
- Plugins: 
  - readmes from plugins should be rendered inside a closeable well, expanded by default. Expand link below action links should read "Show instructions ⬇"
  - action links (install, uninstall, etc) should be rendered as mini buttons.

**Comment by drinks** [comment]
Have a look at this for iconography: http://fortawesome.github.com/Font-Awesome/

**Comment by elcuervo** [comment]
Switching to bootstrap seems to have broken the ACE editor. We looked into it but could not figure out what's the problem yet. Will continue to look into it.

**Comment by foca** [comment]
Ok, the only thing missing from this is better error messages and plugins, but I can't seem to make the chat work. I'll look into it tomorrow.

**Comment by drinks** [comment]
Just fixed the order of bootstrap.css / bootstrap-responsive.css; looks like the top nav needs another look, a la http://twitter.github.com/bootstrap/components.html#navbar

**Comment by drinks** [comment]
Also, the devise login form should follow the 'basic form' pattern here: http://twitter.github.com/bootstrap/base-css.html#forms

**Comment by drinks** [comment]
Can you guys take a look at the email notification workflow? Looks like it remains untouched w/ respect to new styles...

**Comment by elcuervo** [comment]
Can you give me some feedback now? Does it look ok?

**Comment by drinks** [comment]
Well, I'm thrilled that the submission form will now be styled by default, but I was actually referring to the "Notifications" section of event detail page -- the template should be changed to use table_for and the correct button :)

**Comment by elcuervo** [comment]
Oops, sorry about that, i'll fix that in a moment

**Comment by drinks** [comment]
Ok, 3(.5) little things left:
- It looks like all flash messages are getting the base alert class. They should be using error, success and info.
- [This comment](https://github.com/sunlightlabs/datajam/issues/14#issuecomment-4522419) has not yet been incorporated.
- The table update for the notification list looks good, but should use btn-small delete buttons instead of the 'x' link
  - While I'm thinking about it, the rest of the in-table buttons should be .btn-small as well.

**Comment by foca** [comment]
Just using the `delete_button` helper (which I used for all the buttons I found) will make it a `.btn-small`, BTW.

**Comment by drinks** [comment]
Just to be clear, this is the navbar issue: https://skitch.com/dndrnkrd/8k4gx/skitched-20120316-164853

## 

Dan Drinkard

**Comment by elcuervo** [comment]
Ok, i have a question about the first task:
- The flash messages use the alert class as described in here: http://twitter.github.com/bootstrap/components.html#alerts. So success has to be "alert alert-success", what am i missing?

**Comment by drinks** [comment]
Ok, taking a closer look, it may just be devise that is getting alert.alert-alert for all messages. I'm seeing the proper success flash for a template save action now.

**Comment by elcuervo** [comment]
Thanks for the feedback, i've fixed that.
