### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by luigi** [sunlightlabs/datajam#15]
- Will live at datajam.sunlightfoundation.com
- A single page
- Use Twitter Bootstrap 2.0
- Instructions for installation and extension
- Put it in `/docs/index.html` in the project

**Comment by drinks** [comment]
Just an update to this: planning to use gh-pages & jekyll instead of locating files in /docs, which will be reserved for rocco or d

**Comment by drinks** [comment]
Initial page is pushed. Content holes need to be filled, hero at top should be designed/added
