### ISSUE TITLE
Deploy live demo on Heroku

### ISSUE THREAD

**Issue by luigi** [sunlightlabs/datajam#16]
- Use datajam-demo repo on Heroku, will add Bruno and Foca
- Regenerate clean demo data every 10 minutes via rake task called from Heroku scheduler
- Will live at http://datajamdemo.sunlightfoundation.com

**Comment by sbma44** [comment]
Dan or our sysadmin, Tim Ball (tball@sunlightfoundation.com) can help w/ Sunlight's credentials for Heroku.

**Comment by drinks** [comment]
Reseed is done, currently regenerating hourly. Still need more attractive, usable default templates, etc
