### ISSUE TITLE
Content areas should be deleted when removed from a template

### ISSUE THREAD

**Issue by drinks** [sunlightlabs/datajam#2]
- Renaming a content area should cause a new one to be created and the old one to be deleted
- Deleting a content area should cause it to be deleted
- Saving a template with an existing content area should not cause deletion and re-creation

**Comment by elcuervo** [comment]
I think points 1 and 3 are done in this line: https://github.com/sunlightlabs/datajam/blob/master/app/models/event.rb#L140

**Comment by elcuervo** [comment]
I think that this two items are opposed:
- Renaming a content area should cause a new one to be created and the old one to be deleted
- Saving a template with an existing content area should not cause deletion and re-creation

In https://github.com/sunlightlabs/datajam/blob/master/app/models/event.rb#L137-142 new content areas are generated or the existing ones get updated.

I've pushed a commit to clean up unused content_areas (https://github.com/sunlightlabs/datajam/blob/master/app/models/event.rb#L135-136) this fulfills the issue or am i missing something.

**Comment by drinks** [comment]
This looks close to working. The problem I see here is the orm call that initially generates `existing`. It seems to me that it should not care about the `area_type`, and should only `update_attributes` in the `existing.any/else` block if new `area_type` differs from existing `area_type`. Make sense?

As an aside, it may become desirable to add a `status` flag to content areas so they can be included or excluded when rendering a page, without affecting related datasets. For example, If a user has a `chat_area` with a log of messages, perhaps it would be good to not destroy or disassociate them if the chat is renamed or removed. I think this is more a symptom of an interface implementation problem than a technical one, so perhaps let's wait and see how it plays out.
