### ISSUE TITLE
Event Templates can be deleted

### ISSUE THREAD

**Issue by drinks** [sunlightlabs/datajam#22]
Consideration of cascading deletion of template data will necessary.

**Comment by elcuervo** [comment]
If an event template gets deleted what should happened to the event?

**Comment by drinks** [comment]
Good point. This feature is more for fixing mistakes than managing templates. A pre-destroy callback should prevent deletion if any events rely on the template, notifying the user which events depend on it, like this:

"Template could not be deleted. 'SOTU 2012' and 4 other events depend on it."

The event name to be displayed should be truncated to ~15 characters with an ellipsis.

**Comment by elcuervo** [comment]
Perfect, thank you

**Comment by elcuervo** [comment]
And how about Archived Events? they might depend on the template

**Comment by drinks** [comment]
Yep, they should be covered by the same logic. The more I think about this, I'd also like to either not show a delete button unless there are no dependent events, or gray it out with a 'disabled' class.
