### ISSUE TITLE
Handlebars render errors should be caught and displayed to the user

### ISSUE THREAD

**Issue by drinks** [sunlightlabs/datajam#23]
Datajam should not fail with a 500 when a poorly written template is saved.
- handlebars templates should be rendered to strings prior to caching.
- If the render fails, the cache should be left alone, and an error should be flashed to the user

**Comment by drinks** [comment]
I'm not 100% sure this addresses the problem. If a template is saved and turns out to be malformed, content_areas will still be regenerated, etc. before the events' resave calls get interrupted. Is it possible to run the check you're doing in Event as early as the before_save on the Template base class?

**Comment by elcuervo** [comment]
Ok, you are right i'll fix that. Thank you for the feedback

**Comment by drinks** [comment]
You've probably run into this already, but it's worth noting that content areas will always throw render errors as handlebars tries to parse them. These should be stripped before rendering, and each distinct class of content area validated to exist separately.

**Comment by drinks** [comment]
Everything looks great here, save one issue: It's easy to picture a scenario where someone is coding directly in the ace editor without a flat text file backup anywhere. It appears that the template is being reloaded from the database when there is a parse error, meaning that all changes, not just the bug, are lost. Can one small tweak be made to keep the submitted text when returning the edit form after a failed update?

**Comment by elcuervo** [comment]
Sure, i'll fix that right now.

**Comment by elcuervo** [comment]
I think that fixes the issue.
