### ISSUE TITLE
Tagging events and data cards

### ISSUE THREAD

**Issue by drinks** [sunlightlabs/datajam#25]
- Events should be taggable
- Data cards are taggables as well
- Add an admin panel for managing tags.
- When creating an event from the admin, let the creator choose tags with a text field with autocomplete.
- When creating data cards, let the creator choose tags with the same UI as above.
- When selecting data cards from the on-air controls for an event, only data cards which tags intersect the event tags should be selectable.

**Comment by foca** [comment]
I pushed all my changes for this. Everything should be working, sorry @dandrinkard for the delay.

**Comment by drinks** [comment]
I know it's a little unnecessary, but can we add error/success flash messages to the tags admin page for consistency?

**Comment by drinks** [comment]
One less inconsequential request: Can the default behavior for an event with no tags be to include all datacards rather than none? The inverse (datacard with no tags showing up in all events) should not be true. If this completely breaks the model we're built on then let me know ;)

**Comment by foca** [comment]
Done, and done :)

2012/4/26 Dan Drinkard
reply@reply.github.com:
