### ISSUE TITLE
Add sort arrow indicators to sortable table columns

### ISSUE THREAD

**Issue by drinks** [sunlightlabs/datajam#30]

**Comment by drinks** [comment]
font awesome icon-chevron-up and icon-chevron-down should work

**Comment by drinks** [comment]
Couple of notes:
- Arrows are appearing on all columns regardless of whether or not sorting is active on that column. It would be good to display an arrow on the default sort column by default, and then only on the column being sorted when querystring sorting is active.
- Given that the icons are a font, can we change the color of the chevrons to match the column headings' blue?
- Can we place the chevrons to the right of the headings rather than the left?

**Comment by elcuervo** [comment]
I don't quite understand the first bullet point, currently (after fixing the other points) this is how the listing is working:

![Screenshot](http://f.cl.ly/items/462b0t05222I0F0I3z09/Screen%20Shot%202012-04-12%20at%204.53.43%20PM.png)

Name and Scheduled at can be sorted but Status doesn't, should i only enable sorting in the first field?

**Comment by drinks** [comment]
Re: point 1, what I was suggesting is that if the default sort order is by scheduled_at descending, then there should be a down arrow next to the 'scheduled at' heading, but nowhere else. Then if the user clicks the 'name' heading, the arrow would disappear from scheduled at, and instead indicate the direction in which we are sorting by name. Consider iTunes table sorting for an example:

![screenshot](https://img.skitch.com/20120412-dq1tkm67xhji65hpxqtyckgy9a.jpg)

Only the field on which sort is 'active' displays an arrow, the rest would just be links to indicate that they are sortable.

**Comment by elcuervo** [comment]
Great, now i understand. Thank you

**Comment by drinks** [comment]
Nice-to-have, but it would be good to load with an arrow indicating the default sort order, (such as updated_at desc) for templates, etc.
