### ISSUE TITLE
'Archived' events should not be removed from the event list

### ISSUE THREAD

**Issue by drinks** [sunlightlabs/datajam#39]

**Comment by elcuervo** [comment]
Currently an event gets finalized when the user clicks on 'End event', this gets the event in the /archives page, should we change it to 'Archive Event'?

**Comment by drinks** [comment]
I'm not tremendously picky about the button copy, but sure, 'Archive' is
probably more precise.

On Wed, Jun 20, 2012 at 11:29 AM, Bruno Aguirre <
reply@reply.github.com

> wrote:
> 
> Currently an event gets finalized when the user clicks on 'End event',
> this gets the event in the /archives page, should we change it to 'Archive
> Event'?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sunlightlabs/datajam/issues/39#issuecomment-6457962

## 

Dan Drinkard
