### ISSUE TITLE
Static Pages

### ISSUE THREAD

**Issue by luigi** [sunlightlabs/datajam#9]
Add the concept of Pages to the Datajam backend. These are static HTML pages that can be edited in the /admin area. These are useful for an "About" or "Learn More" page for a Datajam instance.
- Create a `Page` model, which has a `slug` and `content` field
  - Ensure that slug values don't conflict with existing ones (from both Events and Pages)
- Create `Admin::PagesController < AdminController`
- Add a Pages section to the /admin area, featuring basic CRUD functionality
- Pages are cached after save using `Cacher.cache`

**Comment by elcuervo** [comment]
I'm assuming that the static HTML pages do not include javascript. Is this correct?

**Comment by elcuervo** [comment]
The content should be rendered between the header and the footer

**Comment by drinks** [comment]
For posterity, reflecting what was discussed in chat: The content field should accept any valid html without a need for escaping by the user, including scripts.

**Comment by elcuervo** [comment]
Implemented in fe26ef9c8d8e82c770ae3de3d047161094956003

**Comment by drinks** [comment]
Only note on this one: slug validation should run against all routes. I was able to define a page at /chats/ with the chat plugin installed, which should either fail validation or display an error message that the page will be unreachable. Routes defined in code should always take precedence over static pages (similar to the behavior of FlatpageFallbackMiddleware in django). Everything else works as expected.
